import "../assets/style/index.scss";
import RootLayoutContainer from "@/components/layouts/RootLayoutContainer";
import { Niramit } from "@next/font/google";
import { Container } from "@mui/material";
import {
  useRouter,
  useSelectedLayoutSegment,
  useSelectedLayoutSegments,
} from "next/navigation";

const Niramit_Font = Niramit({
  weight: "200",
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Niramit_Font.className}>
        <RootLayoutContainer>
          <Container sx={{ position: "relative" }}>
            <div>{children}</div>
          </Container>
        </RootLayoutContainer>
      </body>
    </html>
  );
}
